#!/usr/bin/python -B

# Copyright (C) 2011 - Jonatas Teixeira <jonatast@mandriva.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

import os
import sys
import getopt

path = os.path.abspath(os.path.dirname(sys.argv[0]))
path = os.path.join(path, '..')

if not path in sys.path:
    sys.path.insert(0, path)

if __name__ == "__main__":
   
    from app.views.layout.application import ApplicationLayout
    wizard = ApplicationLayout()

    
