#!/usr/bin/python -B

# Copyright (C) 2011 - Jonatas Teixeira <jonatast@mandriva.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

import os
import sys
import fileinput

def replace_all(file, searchExp, replaceExp):
    for line in fileinput.input(file, inplace=1):
        if searchExp in line:
            line = line.replace(searchExp,replaceExp)
        sys.stdout.write(line)

print "Generating resources file...\t",

path = os.path.abspath(os.path.dirname(sys.argv[0]))
path = os.path.join(path, '..')

respath = os.path.join(path, 'resources')
ressrc = os.path.join(respath, 'wizard.qrc')
resdst = os.path.join(respath, 'wizard_rc.py')

cmd = 'pyrcc4 ' + ressrc + ' -py2 -o ' + resdst + ''
os.system(cmd)

print "Done."

path = os.path.join(path, 'app', 'views')

for dir in os.listdir(path):
    dpath = os.path.join(path, dir)
    
    if not os.path.isdir(dpath):
        continue
        
    for file in os.listdir(dpath):
        fpath = os.path.join(dpath, file)
        basename, extension = os.path.splitext(fpath)

        if extension == '.ui':
            print "Compiling " + fpath + " to " + basename + "_ui.py...\t",
            cmd = 'pyuic4 -o ' + basename + '_ui.py ' + fpath
            os.system(cmd)
            replace_all(basename + "_ui.py", "import wizard_rc", "import resources.wizard_rc")
            print "Done."
